### ISSUE TITLE
CheckList do projeto

### ISSUE THREAD

**Issue by viniciussakai** [viniciussakai/uno-project#1]
- [ ] Iniciar o servidor
- [ ] Inicializar o socket.io
- [ ] Criar o estado global
  - [ ] Criar a tipagems
- [ ] Criar salas
- [ ] Criar o controlador do Jogo
  - [ ] Criar os Baralhos
  - [ ] Misturar e distribuir os baralhos
  - [ ] Jogar carta na mesa
  - [ ] Criar o flow de players
     - [ ] Criar funçao de proximo
     - [ ] Criar funçao d anterior proximo
  - [ ] Funcionalidade de Block
  - [ ] Alterar o fluxo das cartas
  - [ ] Funcionalidade Carta de Compra
  - [ ] Funcionalidade de Cor
  - [ ] Funcionalidade Compra e Cor
  - [ ] Funcionalidade de gritar UNO
  - [ ] Declarar o vencedor
